name: 'Backseat Driver'
description: 'Requests code review from a large language model.'
inputs:
  filenames:
    description: 'The files to pass to the LLM for code review. This value could be one file, several files, or a blob-style path.'
    required: true
  fail-under:
    description: "If specified, exit with non-zero status if the LLM's grade falls below the given value. The value should be one of {'A', 'B', 'C', 'D'}. This value is not inclusive: if this value is 'B' and the LLM gives a final grade of 'B,' then the program will exit with a zero status. If not specified, then the program will exit with a zero status no matter the LLM's grade."
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ "" if not inputs.fail-under else "--fail_under" + inputs.fail-under }}
    - ${{ inputs.filenames }}